name: Deploy DAGs to Local Airflow (Ubuntu)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate DAG Python syntax
        run: |
          for f in $(find dags -name "*.py"); do
            echo "Checking $f"
            python -m py_compile "$f" || (echo "âŒ Syntax error in $f" && exit 1)
          done

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.UBUNTU_SSH_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H ${{ secrets.LINUX_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync DAGs to Ubuntu machine
        run: |
          echo "ðŸš€ Deploying DAGs to ${{ secrets.UBUNTU_USER }}@${{ secrets.LINUX_HOST }}"
          rsync -avz --delete --exclude='.git/' ./dags/ ${{ secrets.UBUNTU_USER }}@${{ secrets.LINUX_HOST }}:${{ secrets.UBUNTU_DAG_PATH }}
